#!/bin/sh
#
# ~/.xinitrc or ~/.xsessionrc
#
# Executed by startx (run your window manager from here)
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

rm /tmp/uzbl*


# Don't activate screensaver
xset s off

# Disable DPMS (Energy Star) features
xset -dpms

# Don't blank the video device
xset s noblank

# Start the matchbox window manager
exec matchbox-window-manager  -use_titlebar no -use_cursor no &
PID=$!

# Let X start and determine the screen size then start uzbl-core
#GEOMETRY=$(xwininfo -display :0.0 -root | grep 'geometry' | awk '{ print $2 }')
sleep 3
#exec /usr/bin/uzbl-core -p https://weather.srly.io/ &
exec /usr/bin/uzbl-core -p http://commondatastorage.googleapis.com/risemedialibrary-395c64e5-2930-460b-881e-009aabb157df/content-templates/teacher-profile/teacher-profile.html &
#exec midori -e Fullscreen -a https://weather.srly.io/
#exec midori -d -e Fullscreen -a http://10.10.10.151:3000/d/K0SArZZRz/mother-pitts?orgId=1&kiosk

# Workaround because status still shows even if set to 0 in config file
sleep 3
FIFO=$(ls -1rt /tmp/uzbl* | tail -1)
#echo 'set geometry = '${GEOMETRY} > ${FIFO}
echo 'set show_status = 0' > ${FIFO} 

wait $PID
